---

dircolors_dest_file: /etc/DIR_COLORS
dircolors_become: yes

homebrew_caskroom_dir: '/usr/local/Caskroom'

# homebrew_taps:
  # - homebrew/dupes
  # - homebrew/science

homebrew_casks:
  - alfred
  - arq
  # - atom
  - beyond-compare
  - dash
  # - docker-beta
  - dropbox
  - forklift
  - google-chrome
  - hammerspoon
  - iterm2
  - karabiner-elements
  - mailmate
  - nvalt
  # - slack
  - spotify

packages:
  # - ansible
  # - awscli
  - curl
  # - fish
  # - fzf
  # - git-extras
  # - git-lfs
  - hugo
  # - hub
  - jrnl
  # - neovim
  # - node
  # - numpy
  # - python
  # - python3
  # - ripgrep
  # - rsync

dns_restart_commands:
  - "dscacheutil -flushcache"
  - "killall -HUP mDNSResponder"
